CREATE TABLE users(
 id BIGINT NOT NULL AUTO_INCREMENT,
 name VARCHAR(150) NOT NULL,
 email VARCHAR(300) NOT NULL,
 phone VARCHAR(25) NULL,
 status INT NOT NULL,
 password VARCHAR(350) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id)
);