CREATE TABLE projects(
 id BIGINT NOT NULL AUTO_INCREMENT,
 name VARCHAR(150) NOT NULL,
 description LONGTEXT NOT NULL,
 status VARCHAR(45) NOT NULL,
 start_date DATETIME NOT NULL,
 end_date DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id)
);