CREATE TABLE tasks(
 id BIGINT NOT NULL AUTO_INCREMENT,
 name VARCHAR(150) NOT NULL,
 details LONGTEXT NULL,
 status VARCHAR(45) NOT NULL,
 expire DATETIME NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id)
);